# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruminate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='ta_name',
            new_name='name',
        ),
    ]
