# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruminate', '0003_auto_20171202_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Office_Hours',
            new_name='Office_Hour',
        ),
    ]
