# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruminate', '0004_auto_20171202_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course_enrolled',
            field=models.ManyToManyField(blank=True, related_name='_user_course_enrolled_+', to='ruminate.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course_teaching',
            field=models.ManyToManyField(blank=True, related_name='_user_course_teaching_+', to='ruminate.Course'),
        ),
    ]
