# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruminate', '0006_office_hour_stream_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_hour',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
